#!/usr/bin/env python
"""Print the brief for day N: everything needed to START writing it, in one small block.

Sources of truth (every line below is copied from one of these, never generated):
  - master plan §13/§14: the phase day N sits in, and the IDs it must close
  - docs/PROGRESS.md: the last row, which fixes what N is allowed to be
  - days/day-NN-<slug>/papers/: which papers are already taught (a paper is taught once)

Replaces reading §14 (12 KB) + TRACEABILITY.md (7 KB) + the previous day's hub and checklist
(39 KB) when all that is wanted is "what am I writing, and may I start?".

    uv run python scripts/brief.py 13
    # prints the assignment, the phase gate, the IDs that should already be closed, and the guard
"""

from __future__ import annotations

import importlib.util
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PLAN = ROOT / "docs" / "00_MASTER_PLAN.md"
PROGRESS = ROOT / "docs" / "PROGRESS.md"
DAYS = ROOT / "days"


def _plan_map() -> dict[int, dict]:
    """Borrow trace.py's §14 reader so the two tools can never disagree about the plan.

    Loaded by path rather than `import trace`, which would shadow the standard library's
    tracer module for anything else importing this file.
    """
    spec = importlib.util.spec_from_file_location("sutra_trace", ROOT / "scripts" / "trace.py")
    if spec is None or spec.loader is None:  # pragma: no cover - only if trace.py is deleted
        raise RuntimeError("scripts/trace.py not found; brief reads the plan through it")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.plan_map()


def day_titles() -> dict[int, str]:
    """The §14 title column, keyed by day. The IDs come from plan_map; this is the prose."""
    out: dict[int, str] = {}
    in_map = False
    for line in PLAN.read_text(encoding="utf-8").splitlines():
        if line.startswith("## 14"):
            in_map = True
        elif in_map and line.startswith("## "):
            break
        elif in_map and (m := re.match(r"\|\s*(\d+)\s*\|([^|]*)\|", line)):
            out[int(m.group(1))] = m.group(2).strip()
    return out


def phase_row(day: int) -> tuple[str, str, str] | None:
    """The §13 row whose day range contains `day`: (phase number, label, gate)."""
    in_map = False
    for line in PLAN.read_text(encoding="utf-8").splitlines():
        if line.startswith("## 13"):
            in_map = True
        elif in_map and line.startswith("## "):
            break
        elif (
            in_map
            and (m := re.match(r"\|\s*(\d+)\s*\|\s*(\d+)[–-](\d+)\s*\|([^|]*)\|([^|]*)\|", line))
            and int(m.group(2)) <= day <= int(m.group(3))
        ):
            return m.group(1), m.group(4).strip(), m.group(5).strip()
    return None


def green_days() -> list[int]:
    """Days with a row in PROGRESS.md. A day with no row is not finished (P2)."""
    rows = [
        int(m.group(1))
        for line in PROGRESS.read_text(encoding="utf-8").splitlines()
        if (m := re.match(r"^\|\s*(\d+)\s*\|", line))
    ]
    return sorted(rows)


def papers_taught() -> dict[str, str]:
    """{identifier: 'title (day folder)'} for every paper already given its own document."""
    out: dict[str, str] = {}
    for md in sorted(DAYS.glob("day-*/papers/*.md")):
        head = md.read_text(encoding="utf-8", errors="replace")[:800]
        pid = re.search(r'^paper:\s*"?([^"\n]+?)"?\s*$', head, re.M)
        title = re.search(r'^title:\s*"?([^"\n]+?)"?\s*$', head, re.M)
        if pid:
            out[pid.group(1)] = f"{title.group(1) if title else '?'} ({md.parent.parent.name})"
    return out


def build(day: int) -> tuple[str, int]:
    """Render the brief for `day`. Returns (text, exit code) - non-zero if N is out of order."""
    plan, titles, green = _plan_map(), day_titles(), green_days()
    out = [
        f"# Day {day} brief",
        "",
        "_Generated by scripts/brief.py; every line is copied from a "
        "source file. Read plan §17 and the addenda in full before writing._",
        "",
    ]

    out += ["## Plan §14 - the assignment", ""]
    for d in (day - 1, day, day + 1):
        if d in titles:
            marker = "->" if d == day else "  "
            ids = ", ".join(plan.get(d, {}).get("ids", [])) or "—"
            out.append(f"{marker} day {d}: {titles[d]}  [{ids}]")
    target = plan.get(day, {}).get("ids", [])
    out += [
        "",
        f"**Close exactly these IDs, no more and no fewer:** {', '.join(target) or '—'}",
        "",
    ]

    if row := phase_row(day):
        out += [f"## Phase {row[0]} - {row[1]}", "", f"Gate: {row[2]}", ""]

    # An ID assigned to an earlier day that is still open is a bug, not a backlog item.
    overdue = [
        (d, plan[d]["ids"]) for d in sorted(plan) if d < day and d not in green and plan[d]["ids"]
    ]
    out += ["## IDs that should already be closed", ""]
    if overdue:
        out += [
            f"- 🐛 day {d} has no PROGRESS row, so {', '.join(ids)} are open" for d, ids in overdue
        ]
    else:
        out.append("- none; every day before this one is green")
    out.append("")

    out += ["## Papers already taught (cite and link these; never teach one twice)", ""]
    out += [f"- `{k}` — {v}" for k, v in sorted(papers_taught().items())] or ["- none yet"]
    out.append("")

    last = green[-1] if green else -1
    prior = ROOT / "docs" / "wiki" / f"day-{last:02d}.md"
    out += [
        "## Where we are",
        "",
        f"- last PROGRESS row: day {last}",
        f"- previous day in one page: `{prior.relative_to(ROOT).as_posix()}`"
        + ("" if prior.exists() else "  (missing - run `./m wiki`)"),
        "",
    ]

    if day != last + 1:
        out += [
            f"**STOP.** The last PROGRESS row is day {last}, so N must be {last + 1}, "
            f"not {day}. Fix the ledger or the day number before writing (P2).",
            "",
        ]
        return "\n".join(out), 1
    out += [f"**Guard OK.** Day {day} is exactly one more than the last row.", ""]
    return "\n".join(out), 0


def main() -> int:
    if len(sys.argv) != 2 or not sys.argv[1].isdigit():
        print("usage: uv run python scripts/brief.py <day>")
        return 1
    text, code = build(int(sys.argv[1]))
    sys.stdout.reconfigure(encoding="utf-8")  # the brief carries — and 🐛; cp1252 cannot
    print(text)
    return code


if __name__ == "__main__":
    sys.exit(main())
